
import java.awt.Image;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hanzala
 */


public class Main_page extends javax.swing.JFrame {

    /**
     * Creates new form Main_page
     */
    public Main_page() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Student_pf = new javax.swing.JLabel();
        Delete_student = new javax.swing.JLabel();
        New_adm = new javax.swing.JLabel();
        fee_pay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M.H School Management");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Student_pf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Student_pf.setIcon(resizedImage(new javax.swing.ImageIcon(getClass().getResource("/graduated.png")),40,40));
        Student_pf.setText("Student profile");
        Student_pf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Student_pf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Student_pfMouseClicked(evt);
            }
        });

        Delete_student.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Delete_student.setIcon(resizedImage(new javax.swing.ImageIcon(getClass().getResource("/remove.png")),40,40));
        Delete_student.setText("Remove Student");
        Delete_student.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_studentMouseClicked(evt);
            }
        });

        New_adm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        New_adm.setIcon(resizedImage(new javax.swing.ImageIcon(getClass().getResource("/new_person.png")),40,40));
        New_adm.setText("New Admission");
        New_adm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        New_adm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_admMouseClicked(evt);
            }
        });

        fee_pay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fee_pay.setIcon(resizedImage(new javax.swing.ImageIcon(getClass().getResource("/fee.png")),40,40));
        fee_pay.setText("Fee payment");
        fee_pay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fee_pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fee_payMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(New_adm, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Student_pf, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fee_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(Delete_student, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(New_adm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_pf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fee_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_student, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("M.H School Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void New_admMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_admMouseClicked
new Admission_form().setVisible(true);
//this.setEnabled(false);
System.out.println("Opened");

    }//GEN-LAST:event_New_admMouseClicked

    private void Student_pfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_pfMouseClicked
        new Edit_Page().setVisible(true);
    }//GEN-LAST:event_Student_pfMouseClicked

    private void fee_payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fee_payMouseClicked
new FeePayment_Page().setVisible(true);
    }//GEN-LAST:event_fee_payMouseClicked
SqlConnection connect = new SqlConnection();
    private void Delete_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_studentMouseClicked
String e =JOptionPane.showInputDialog(this,"Enter Gr_NO:");
try{
int gr = Integer.parseInt(e);
int r =JOptionPane.showConfirmDialog(this, "Are you sure you want to remove Gr NO: "+gr+" from school record", e, JOptionPane.YES_NO_OPTION);
if(r!=1){
    
boolean done = connect.Remove_Student(gr);
if(!done){
JOptionPane.showMessageDialog(this, "This Gr NO does not have any record");
}
else{
JOptionPane.showMessageDialog(this, "Successfully deleted");
}
}

}catch(NumberFormatException r ){
JOptionPane.showMessageDialog(this, "Enter valid value");
}

    }//GEN-LAST:event_Delete_studentMouseClicked
public ImageIcon resizedImage(ImageIcon img , int height , int width){
Image imeg =((img.getImage()).getScaledInstance(width, height, Image.SCALE_SMOOTH));
return new ImageIcon(imeg);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_page().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Delete_student;
    private javax.swing.JLabel New_adm;
    private javax.swing.JLabel Student_pf;
    private javax.swing.JLabel fee_pay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
